export const dark = "#000000"
export const accent = "rgb(216, 38, 62)";
export const pure = "#FFFFFF";
export const lightGrey = "#D6D6D6";
export const gainsBoro = "#DBDBDB";
export const darkGrey = "#A7A7A7";
export const blackCurrent = "#19171a";
export const placeholdeColor = "#B8B8B8";
export const inputBorderColor = "#BBBBBB";
export const paraColor = "#19171a";